import { task } from "@trigger.dev/sdk";
import Anthropic from "@anthropic-ai/sdk";
import { Resend } from "resend";

// ── Daily Market Analysis ─────────────────────────────────────────
// Scheduled: Daily at 7:30am ET (via daily-morning orchestrator)
// Analyzes market conditions and sends email report

const WATCHLIST_STOCKS = ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "TSLA", "META", "AMD", "SPY", "QQQ"];
const WATCHLIST_CRYPTO = ["BTC/USD", "ETH/USD", "SOL/USD"];

export const dailyMarketAnalysis = task({
  id: "daily-market-analysis",
  run: async () => {
    const anthropic = new Anthropic();

    // Ask Claude to generate a market briefing
    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 2000,
      messages: [
        {
          role: "user",
          content: `You are an elite market strategist. Generate a morning market briefing for ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}.

Watchlist: ${WATCHLIST_STOCKS.join(", ")} and crypto: ${WATCHLIST_CRYPTO.join(", ")}

Provide:
1. Market outlook for today (2-3 sentences)
2. Key events/earnings to watch
3. Top 3 trade ideas with entry/target/stop levels
4. Risk warnings
5. Crypto outlook

Format as HTML for email. Use a clean, dark-themed design with:
- Green (#34d399) for bullish signals
- Red (#fb7185) for bearish signals
- Purple (#a78bfa) for AI insights
Keep it concise and actionable. No disclaimers.`,
        },
      ],
    });

    const briefingHtml =
      message.content[0].type === "text" ? message.content[0].text : "";

    // Send email via Resend
    const resendKey = process.env.RESEND_API_KEY;
    const recipientEmail = process.env.MARKET_ALERT_EMAIL;

    if (resendKey && recipientEmail) {
      const resend = new Resend(resendKey);

      await resend.emails.send({
        from: "Apex Markets <alerts@apexbrain.ai>",
        to: recipientEmail,
        subject: `Market Briefing — ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric" })}`,
        html: `
          <div style="background: #0f0f19; color: #e2e8f0; font-family: -apple-system, sans-serif; padding: 32px; border-radius: 12px;">
            <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 24px;">
              <div style="width: 8px; height: 8px; border-radius: 50%; background: #34d399;"></div>
              <h1 style="margin: 0; font-size: 18px; color: white;">Apex Markets — Daily Briefing</h1>
            </div>
            ${briefingHtml}
            <hr style="border: none; border-top: 1px solid rgba(255,255,255,0.1); margin: 24px 0;" />
            <p style="font-size: 11px; color: rgba(255,255,255,0.3);">
              Generated by Apex Brain AI at ${new Date().toISOString()} • Paper trading mode
            </p>
          </div>
        `,
      });

      console.log(`Market briefing sent to ${recipientEmail}`);
    }

    return {
      status: "complete",
      timestamp: new Date().toISOString(),
      briefingLength: briefingHtml.length,
      emailSent: !!(resendKey && recipientEmail),
    };
  },
});

// ── Market Alert Scanner ──────────────────────────────────────────
// Checks for significant price movements and sends alerts

export const marketAlertScanner = task({
  id: "market-alert-scanner",
  run: async () => {
    // This task would be triggered by the daily-morning orchestrator
    // or can be run on its own schedule for intraday alerts

    const polygonKey = process.env.POLYGON_API_KEY;
    if (!polygonKey) {
      return { status: "skipped", reason: "POLYGON_API_KEY not configured" };
    }

    const alerts: Array<{ symbol: string; type: string; message: string }> = [];

    // Check each stock for significant moves
    for (const symbol of WATCHLIST_STOCKS) {
      try {
        const res = await fetch(
          `https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers/${symbol}?apiKey=${polygonKey}`
        );
        const data = await res.json();
        const ticker = data.ticker;

        if (!ticker) continue;

        const changePercent = ticker.todaysChangePerc || 0;

        // Alert on moves > 3%
        if (Math.abs(changePercent) > 3) {
          alerts.push({
            symbol,
            type: changePercent > 0 ? "surge" : "drop",
            message: `${symbol} ${changePercent > 0 ? "surged" : "dropped"} ${Math.abs(changePercent).toFixed(1)}% today`,
          });
        }
      } catch {
        // Continue on individual stock failures
      }
    }

    // Send email if we have significant alerts
    if (alerts.length > 0 && process.env.RESEND_API_KEY && process.env.MARKET_ALERT_EMAIL) {
      const resend = new Resend(process.env.RESEND_API_KEY);

      const alertHtml = alerts
        .map(
          (a) =>
            `<div style="padding: 8px 12px; margin: 4px 0; background: ${a.type === "surge" ? "rgba(52,211,153,0.1)" : "rgba(251,113,133,0.1)"}; border-radius: 6px; border-left: 3px solid ${a.type === "surge" ? "#34d399" : "#fb7185"};">
              <strong style="color: white;">${a.symbol}</strong>
              <span style="color: rgba(255,255,255,0.7); font-size: 13px;"> — ${a.message}</span>
            </div>`
        )
        .join("");

      await resend.emails.send({
        from: "Apex Markets <alerts@apexbrain.ai>",
        to: process.env.MARKET_ALERT_EMAIL,
        subject: `Market Alert: ${alerts.length} significant move${alerts.length > 1 ? "s" : ""} detected`,
        html: `
          <div style="background: #0f0f19; color: #e2e8f0; font-family: -apple-system, sans-serif; padding: 24px; border-radius: 12px;">
            <h2 style="margin: 0 0 16px; font-size: 16px; color: white;">Market Alerts</h2>
            ${alertHtml}
            <p style="font-size: 11px; color: rgba(255,255,255,0.3); margin-top: 16px;">
              ${new Date().toISOString()} • Apex Brain AI
            </p>
          </div>
        `,
      });
    }

    return {
      status: "complete",
      alertCount: alerts.length,
      alerts,
      timestamp: new Date().toISOString(),
    };
  },
});
